#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."

export DOTFILES=$HOME/.dotfiles

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

curl -s https://raw.githubusercontent.com/nunorafaelrocha/dotfiles/master/script/bootstrap
unzip to $DOTFILES

cd $DOTFILES

if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi
